parameters:
#    ste_beatracker.example.class: Stems\SaleSirenBundle\Example

services:
#    ste_beatracker.example:
#        class: %ste_beatracker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
